### ISSUE TITLE
[Request] ability to change send button colour

### ISSUE THREAD

**Issue by mamba831** [CreatureSurvive/bubbles#11]
I have the bubbles match the colour of my background so it’ll hide the bubbles and the text coloured to indicate whether it’s sms or iMessage. Is it possible for the send button to match the colour of the texts by adding an option to configure the button colour?

**Comment by mamba831** [comment]
Also please allow customization of typing indicator or match the colour of the send button. Thanks

**Comment by CreatureSurvive** [comment]
this was added in v0.1.9, i'm a bit late closing the issue :)
