### ISSUE TITLE
Transparent Background for Contacts

### ISSUE THREAD

**Issue by mttyptty** [CreatureSurvive/bubbles#15]
When you go to your contacts information in messages the background is transparent

**Comment by CreatureSurvive** [comment]
@mttyptty I added a temporary fix for this (still has a bug when scrolling). I think I found an official solution, so I'll be looking into it tomorrow.

**Comment by CreatureSurvive** [comment]
@mttyptty I added a proper fix for this just now, so the background is the same blur as in the conversation details view.

![img_0264](https://user-images.githubusercontent.com/5193275/43218795-0fd1faee-900b-11e8-8828-e1f250d81e79.png)

Closing this issue

**Comment by mttyptty** [comment]
So cool! Thanks! 😊

**Comment by swang530** [comment]
I'm still showing transparent details. What settings should I be updating?
