### ISSUE TITLE
Bubbles Tweak Issue

### ISSUE THREAD

**Issue by ashley108** [CreatureSurvive/bubbles#16]
Having the navigation bar set as alpha it still is full color not showing as alpha

**Comment by CreatureSurvive** [comment]
@ashley108 the navigation bar has a blurred background which doesn't respect the alpha channel, I'll look into adding an option to disable navigation bar blur.

**Comment by CreatureSurvive** [comment]
added option to remove navigation bar blur in v0.2.4b, closing this now
