### ISSUE TITLE
[Request] Colour options for contact numbers

### ISSUE THREAD

**Issue by mamba831** [CreatureSurvive/bubbles#17]
When typing a number on the send to field, the colour of the names and numbers of the contact still matches the colour of the bubbles set. Since my background and bubbles are the same colour (to hide the bubbles), the contacts can't be seen. Please add an option to change the colours for sms vs imessage contacts.

As shown in the image, the name blends in with the background as it matches the colour of the bubble for imessage which i set to black.

![img_0245](https://user-images.githubusercontent.com/38694228/43148747-83e43f46-8f98-11e8-8b8d-b7cd98dd18e3.png)

**Comment by CreatureSurvive** [comment]
@momba832 I will look into this tomorrow, thanks for reporting this.

**Comment by CreatureSurvive** [comment]
@mamba831 I just implemented coloring options for all contact names in the compose view (iMessage/SMS/Default) so you can customize to your liking. It will be included in today's update. thanks for reporting the issue. I'll be closing this now.
