### ISSUE TITLE
Navbar and message bubbles’ colours properly not being applied

### ISSUE THREAD

**Issue by nigrr** [CreatureSurvive/bubbles#18]
Depiction: https://imgur.com/a/S2zuLTw

**Comment by Jehicular** [comment]
This is due to the fact that the response is 3 or less characters. Messages of 3 or less characters fill the bubble despite the 'Outline' option being checked. Since your text color and bubble color are both white, there's our problem.

**Comment by CreatureSurvive** [comment]
@nigrr @Jehicular I just found a solution to this issue, it will be included in today's update.
