### ISSUE TITLE
Attachments messing with bubbles when “outline only” is enables

### ISSUE THREAD

**Issue by MYV** [CreatureSurvive/bubbles#19]
Whenever I send or receive a picture the next message becomes filled instead of having just the outline like the rest

**Comment by MYV** [comment]
Nvm it only happens when I send a message that’s 3 characters or less

Sent from my iPhone

On Jul 27, 2018, at 6:25 PM, Jehicular <notifications@github.com<mailto:notifications@github.com>> wrote:


It works for me, I am using the dark mode. Could you link a screenshot?

**Comment by CreatureSurvive** [comment]
@MYV @Jehicular I just found a solution to this issue, it will be included in today's update.
