### ISSUE TITLE
iMessage and SMS bubles coloring doesn't work when light theme is selected since last update

### ISSUE THREAD

**Issue by LOLXDXPLOL** [CreatureSurvive/bubbles#20]
https://i.imgur.com/OeNnaH0.jpg

**Comment by CreatureSurvive** [comment]
@LOLXDXPLOL I'm aware of the issue, hopefully, I'll have it fixed in today's update. I'm not able to reproduce the issue on my own device so its a bit tricky to test

**Comment by CreatureSurvive** [comment]
@LOLXDXPLOL v0.2.2b is finally out, which fixes this issue. Sorry for the delay.
