### ISSUE TITLE
Border only on Conversation List/Issue with 3 letter words being completely filled in.

### ISSUE THREAD

**Issue by nahtedetihw** [CreatureSurvive/bubbles#21]
So your tweak bubbles is amazing!
I just wanted to put in a request and let you know of an issue.
Request: Would you be able to put the border only on the conversation list as well?
Issue: When typing 3 letter words or less and sending, it fills he bubble in completely instead of having the border only in chat view.

**Comment by CreatureSurvive** [comment]
@nahtedetihw I just found a solution for this issue, it was a tricky one. hoping to get an update out by the end of the day addressing this and a few other issues!

**Comment by nahtedetihw** [comment]
Awesome, thank you!
Also after updating  libCScolorpicker and libCSpreferences, my settings app crashes. I downgraded them and it started working again just wanted you to know.

**Comment by CreatureSurvive** [comment]
@nahtedetihw the issue with libCSPreferences causing crashes has been fixed. I released v0.9.9.8 a few hours ago to address this issue.

**Comment by nahtedetihw** [comment]
Ok great! Glad to know it’s safe to update:)

**Comment by CreatureSurvive** [comment]
@nahtedetihw v0.2.2b is finally out with a fix for this issue, sorry for the delay.
