### ISSUE TITLE
Bubbles broke Termius 

### ISSUE THREAD

**Issue by pr0xee** [CreatureSurvive/bubbles#22]
After installation (including dependencies) it broke Termius app; if uninstall bubbles and dependencies then termius works again. Where is the relation for this problem?

**Comment by CreatureSurvive** [comment]
@pr0xee This was an issue due to an update to libCSPreferences (v0.9.9.7), I've since released version 0.9.9.8 which fixes this issue. Sorry for the inconvenience.

**Comment by pr0xee** [comment]
Perfect, i noticed that thanks! Working ok now.

A domingo, 29 de jul de 2018, 22:36, Dana Buehre <notifications@github.com>
escreveu:
