### ISSUE TITLE
Black navbar turns white when composing new message

### ISSUE THREAD

**Issue by mattperr827** [CreatureSurvive/bubbles#25]
The navbar turns white when composing a new message, but returns to black after exiting the message. It doesn’t turn white until a contact is selected.

**Comment by CreatureSurvive** [comment]
@mattperr827 Could you send me a support email so that i can look into this further?

**Comment by mattperr827** [comment]
Sent. Sorry for the delay.

**Comment by CreatureSurvive** [comment]
possible duplicate of #27

**Comment by mattperr827** [comment]
Yes, confirmed. This was also caused by BarinProgess.

**Comment by CreatureSurvive** [comment]
Nice, thanks for the confirmation. I might have a small update out tonight with a few new features and fixes.

**Comment by mattperr827** [comment]
Awesome. Looking forward to it!
