### ISSUE TITLE
With "Bubble Borders Only (No Fill)" enabled, SMS/iMessage text on your side dissapears

### ISSUE THREAD

**Issue by dstlny** [CreatureSurvive/bubbles#26]
https://imgur.com/a/ghgL6cM - you can see that here, with setting off text appears - with it on, it's broken and doesnt actually appear.

**Comment by CreatureSurvive** [comment]
@dstIny this is actually an issue with your configuration, you have tryout text color set to white for 'iMessage Text' which is the same color as your background. You'll just need to change the text color to resolve this.
