### ISSUE TITLE
Black navigation bar turns white when rotating your screen to landscape and then stays white when you go back into portrait mode

### ISSUE THREAD

**Issue by iAppleLuvr** [CreatureSurvive/bubbles#27]
iPhone X, 11.4 b3

https://imgur.com/a/SOOaomF

**Comment by CreatureSurvive** [comment]
@iAppleLuvr That's strange, I can't seem to replicate this bug on my device (iPhone X 11.3.1). It could be related to 11.4, or it could be due to another tweak interfering. Could you send me a send me a support email, so I can rule out a tweak conflict before I start looking into 11.4 SDK changes?

**Comment by ghost** [comment]
@CreatureSurvive Done, thanks!

**Comment by mattperr827** [comment]
I am able to replicate the issue on iOS 11.2.1.

**Comment by avitzavi** [comment]
Also have this issue on 11.1.2 iPX. Happy to help diagnose and supply a tweak list.

**Comment by CreatureSurvive** [comment]
@avitzavi yeah, if you could send me a tweak list that would be helpful

**Comment by ghost** [comment]
Clearly, it isn't an issue with 11.4. Maybe with a conflicting tweak, as my friend (6s, 11.3.1) cannot replicate this issue either. It probably isn't something with the iPX because you have one and it works fine for you.

**Comment by avitzavi** [comment]
My issue is on the iPX. Appluvr, do you have [[meNoWrite]] or barmoji installed?

**Comment by mattperr827** [comment]
I also have an iPX and I have barmoji installed.

**Comment by CreatureSurvive** [comment]
Doesn't seam to be caused by barmoji, just tested and I still can't reproduce the issue

**Comment by CreatureSurvive** [comment]
Not MeNoWrite either

**Comment by mattperr827** [comment]
I also have BarinProgress, NoMoreAppBar, and SendDelay for tweaks that affect the Messages app.

**Comment by avitzavi** [comment]
Uninstalled barmoji and MeNoWrite and it still occurs. IPX 11.1.2

**Comment by CreatureSurvive** [comment]
There we go, it's BarinProgress. I'll see if I can just add that as a feature to bubbles, or resolve the conflict.

**Comment by avitzavi** [comment]
Confirmed. BarInProgress is the conflict.

**Comment by ghost** [comment]
@avitzavi Nice find! Just removed it and now Bubbles is working perfectly! Thanks :)

**Comment by CreatureSurvive** [comment]
well, that was easy, SMS progress indicators will be a feature in the next update.
![bubbles_sms_progress_bars](https://user-images.githubusercontent.com/5193275/44238207-4ffe9800-a179-11e8-8d9e-e661b7d93c95.gif)

**Comment by avitzavi** [comment]
iMessage too? =p

**Comment by CreatureSurvive** [comment]
iMessage already has this built in

**Comment by avitzavi** [comment]
In iOS 11 the bar only shows if there’s a poor connection
