### ISSUE TITLE
Reaction bubble unreadable 

### ISSUE THREAD

**Issue by BoBoMaster13** [CreatureSurvive/bubbles#28]
When selecting a text to react (thumbs up, thumbs down etc) the bubble is white and cannot see selections. See image: https://imgur.com/a/OnDLQHz

**Comment by IsoPhoenix** [comment]
Also having this issue.

**Comment by sobersherlock** [comment]
this worked in 0.2.4 but appears again in 0.3.0

**Comment by mohammad-sajjad11** [comment]
Yes same.

**Comment by Jato-BZ** [comment]
Also here 0.30b iPhone X - iOS 11.3.1 no Eclipse installed or other dark mode tweaks. Annoying to try work out what reactions are what when the bubble is completely white. Any idea if there is update in the works to address? Thanks

**Comment by solomone212** [comment]
I have the same issue.
