### ISSUE TITLE
Crashes in settings 

### ISSUE THREAD

**Issue by OneCruelSOB** [CreatureSurvive/bubbles#31]
**Describe the bug
iOS 11.3.1 iPad Pro
When you open the settings and select dark mode or light mode it crashes springboard and then it makes all the tweaks disappear this happens on Version 0.2.2b. When I downgrade to 0.2.0b no problems at all.

**Comment by CreatureSurvive** [comment]
@OneCruelSOB is this still an issue in v0.2.4? Bubbles no longer targets anything in Springboard, so this may be resolved now.

**Comment by CreatureSurvive** [comment]
closing for now, i've not had any reports of this since releasing v0.2.2b
