### ISSUE TITLE
iMessage games and app bubbles not visible when borders only mode is active

### ISSUE THREAD

**Issue by larehan** [CreatureSurvive/bubbles#32]
iMessage games and app bubbles not visible when borders only mode is active

**Comment by larehan** [comment]
https://drive.google.com/open?id=1kKeN-qxJCxyK49UlaAvws1a7T2C0hGA-

**Comment by bigfoott** [comment]
I'm also having this issue. Tapping in the empty spot still opens the game though

**Comment by larehan** [comment]
Yes but it looks weird

**Comment by CreatureSurvive** [comment]
I'll see what I can do to fix this in today's update, trying to get every bug squashed in this version.

**Comment by CreatureSurvive** [comment]
Fixed, will be included in tonight's update.
