### ISSUE TITLE
Perseverant background image. 

### ISSUE THREAD

**Issue by larehan** [CreatureSurvive/bubbles#33]
I tried the background image once but then I disabled chat and list background. However the background I previously used and disabled will appear whenever I start a new conversation or when I receive or send an iMessage effect.

**Comment by larehan** [comment]
https://drive.google.com/open?id=1widK3maqb_eMzGsUFNrvbeUIM_V1wN6c

**Comment by larehan** [comment]
https://drive.google.com/open?id=1eI3Q_G__8D37TNdpHZYPNx1q32nR3iea

**Comment by larehan** [comment]
https://drive.google.com/open?id=1ritRp426BzECK951jWUSJBLclZOOZS21

**Comment by CreatureSurvive** [comment]
Fixed, will be included in tonight's update.
