### ISSUE TITLE
Ability to add or remove the contact photos in group chats

### ISSUE THREAD

**Issue by sirmahimahi** [CreatureSurvive/bubbles#34]
Allow users to remove the circle photos next to names when they are texting in a group chat. This i think would make it a lot cleaner like a normal 1 on 1 conversation.

**Comment by CreatureSurvive** [comment]
@binkbankbonk got it, will be included in the next update.

**Comment by CreatureSurvive** [comment]
whoops, didn't mean to close this

**Comment by CreatureSurvive** [comment]
Actually there will only be an option to remove them for now.
