### ISSUE TITLE
Sticker borders. 

### ISSUE THREAD

**Issue by larehan** [CreatureSurvive/bubbles#35]
When on borders only mode, sending a sticker from a new message will come with the border around the sticker. 

This does not affect the sticker when you drag and on on an existing bubble. This only happens with the borders only option enabled.

**Comment by larehan** [comment]
https://drive.google.com/open?id=1VI0sAgvhxF29RPSOwRIzq1hfHzHwp3Ql

**Comment by CreatureSurvive** [comment]
@larehan I'll look into it, thanks for letting me know.

**Comment by CreatureSurvive** [comment]
Fixed, will include in tonight's update.
