### ISSUE TITLE
Black screen when sending a message on Dark conf

### ISSUE THREAD

**Issue by larehan** [CreatureSurvive/bubbles#36]
When I send a message on dark configuration, screen will go back for a brief moment. This does not happen on black configuration.

**Comment by larehan** [comment]
https://drive.google.com/open?id=1SMqZVc4whOyy4Snu-16o_ZEI-pgk8xuA

**Comment by CreatureSurvive** [comment]
@larehan I'm aware of the issue, and I'll be looking into it this evening.

**Comment by larehan** [comment]
Great! This is one of the best tweaks even in a beta version. Congrats on this amazing work

**Comment by CreatureSurvive** [comment]
Looks like this bug is caused by having a background image set for the chat view, I'm looking into fixes right now.

**Comment by CreatureSurvive** [comment]
@larehan thanks, I appreciate that!

**Comment by CreatureSurvive** [comment]
@larehan thanks, I appreciate that!

**Comment by CreatureSurvive** [comment]
For anyone wanting to resolve this issue until I get the next update out, you'll have to delete and disable you're background chat background image. If you're not aware of how to delete the photo, just watch this [demo](https://creaturecoding.com/shared/bubbles_delete_background_image.mov)

**Comment by CreatureSurvive** [comment]
Fixed, this should also improve memory usage in the next version.
