### ISSUE TITLE
Overlap the line

### ISSUE THREAD

**Issue by abdalkareim** [CreatureSurvive/bubbles#37]
When i to try to add a contact van stock message aap i got two overlap screen (the first is the message screen and the second is where i can the new contact can add 
Unfortunately here i can’t add photo or video to make it simpler..
A lot of thanks for your nice tweak
Abdalkareim Wrar

**Comment by CreatureSurvive** [comment]
@abdalkareim I'll be looking into this tonight, thanks for reporting.

**Comment by CreatureSurvive** [comment]
Fixed, will include in tonight's update.

**Comment by abdalkareim** [comment]
Perfect sir 😍 a lot of thanks 🙏

On 18 Aug 2018, at 03:38, Dana Buehre <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed, will include in tonight's update.
