### ISSUE TITLE
2.4b no color for Contacts 

### ISSUE THREAD

**Issue by Beezure** [CreatureSurvive/bubbles#39]
When typing name from compose, the contacts are not colored (iMessage or sms ) they are all white . 2.2 version works fine

**Comment by CreatureSurvive** [comment]
@Beezure this is intentional for the black configuration, you can change the colors in the settings if you prefer.

**Comment by Beezure** [comment]
But this is when using dark ! Should it be that way in dark mode also? The colors are selected in dark mode settings!

**Comment by CreatureSurvive** [comment]
Strange, it's working fine for me. I'll look into it.

**Comment by Beezure** [comment]
Yeah it started working normal for me now also !!
