### ISSUE TITLE
iMessage App drawer persists on 0.2.8 onward

### ISSUE THREAD

**Issue by sobersherlock** [CreatureSurvive/bubbles#45]
What the title says. App drawer stays there even when the keyboard is invoked. It worked fine on 0.2.4 so that's where I'm staying for the time being. I don't wanna toggle disable app bar on, so that's not an option for me
![img_1797](https://user-images.githubusercontent.com/37182976/44399797-0cd66780-a573-11e8-8834-c8645ef3b745.PNG)

**Comment by CreatureSurvive** [comment]
just fixed this in v0.3.0b, thanks for reporting!

**Comment by sobersherlock** [comment]
thanks for fixing this!
