### ISSUE TITLE
Error loading preference bundle

### ISSUE THREAD

**Issue by serspencer** [CreatureSurvive/bubbles#67]
**Describe the bug**
Preference bundle loading error.

**To Reproduce**
1. Go to 'settings'
2. Click on 'Bubbles'
4. See error "There was an error loading the preference bundle for Bubbles"

**Expected behavior**
The settings are suppose to open.

**Smartphone (please complete the following information):**
 - Device: iPhoneXs
 - iOS: iOS 12.0.1
 - Version 0.4.0

**Comment by CreatureSurvive** [comment]
This is fixed in version 0.5 it's available on https://creaturecoding.com/repo/

**Comment by serspencer** [comment]
Just found it, I appreciate it.  I needed to update two other sources and I am all good now.  Thank you very much for the quick reply. 

Cheers :)

**Comment by CreatureSurvive** [comment]
Not a problem, glad to help.
