### ISSUE TITLE
Contact Photo Issues in Mesaage 

### ISSUE THREAD

**Issue by wontknowyou** [CreatureSurvive/bubbles#76]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - iOS: [e.g. iOS 11.3.1]
 - Version [e.g. 0.2.2b]

**Additional context**

**Comment by wontknowyou** [comment]
After the latest Bubbles updated the contact photo within the message convo is grey, no photo visible.

**Comment by CreatureSurvive** [comment]
Fixed in version 0.5.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
