### ISSUE TITLE
Conversation list background color not changing

### ISSUE THREAD

**Issue by princesskhloee** [CreatureSurvive/bubbles#8]
The conversation list background color won't change. Just stays white.

**Comment by CreatureSurvive** [comment]
@princesskhloee I'll look into this right now.

**Comment by CreatureSurvive** [comment]
@princesskhloee I'm going to close this issue since I haven't heard back from you yet, and I've not had any more reports about this. If you're still experiencing this bug, feel free to send a Support email, or create a new issue.
